name: Publish Quarto Website

on:
  push:
    branches: [ main ] # Trigger on push to main branch
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # You can specify a Quarto version here if needed:
        # with:
        #   version: 1.4.553 # Example version

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Render Quarto Website
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # Render to HTML
          # Ensure output-dir matches _quarto.yml if specified
          # path: . # Render the root directory

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs # Use the output directory specified in _quarto.yml

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 